### ISSUE TITLE
【提问】能否生成NPC角色

### ISSUE THREAD

**Issue by yehuoshun** [Penelopeep/CharacterBuilder#1]

**Comment by Penelopeep** [comment]
你好，我們可以說英語嗎？因為我不會寫中文。如果我寫錯了，我很抱歉，我是用翻譯器翻譯的。

**Comment by yehuoshun** [comment]
NPC create And use

**Comment by Penelopeep** [comment]
Did you meant to create new character and equip them with new items?

**Comment by yehuoshun** [comment]
For example：create Catherine 
I can Control Catherine movement

**Comment by Penelopeep** [comment]
They're few things to note about that:
1. Catherine and other NPCs (like shop assistants) aren't playable and the only way possible to get "something" is to change models which isn't possible in Grasscutter.
2. And if I were to add something like this with existing characters then I'd need to rewrite my plugin. And it would raise even more problems. For example which build would you want on your "generated" Xiangling?
3. It's not the purpose of this plugin. It's made to make building characters a little bit easier
