### ISSUE TITLE
Can I use it on GrassCutter Version 2.2? It seems meet some issues.

### ISSUE THREAD

**Issue by andoloido** [Penelopeep/CharacterBuilder#2]
![image](https://github.com/Penelopeep/CharacterBuilder/assets/52614822/45308036-39a1-41c5-a802-39aebf97b593)

**Comment by Penelopeep** [comment]
Hi, what do you mean by version 2.2?
The current newest version of Grasscutter is 1.7.1, also I haven't seen this type of error so you have to give me some more information.

**Comment by andoloido** [comment]
I'm sorry that I didn't use the formal version of grasscutter. I will try to solve this error my self. Thank you very much!

**Comment by Penelopeep** [comment]
It's not a problem, if this is a publicly available version then you can send me it so I can try to fix for you
