### ISSUE TITLE
Custom Builds Cause Plugin to Break

### ISSUE THREAD

**Issue by Stanstillplays** [Penelopeep/CharacterBuilder#4]
Hello, I understand that this might be because I am playing With Grasscutter 1.7.4 and you said it wasn't tested on there or that I'm bad at coding but I have added a few custom builds to the plugin and after reloading it it refuses to list the builds in game, I'm not sure if it is because I'm playing without opencommand but I am having issues with that plugin and my server so I will have to find out why but as I said earlier it refuses to list the builds, I've tried to reset the builds config and it seems to work fine so maybe I am just doing it wrong, but anyway I guess some help or insight into the matter will be helpful. Thank you.

**Comment by NotThorny** [comment]
> I'm not sure if it is because I'm playing without opencommand

This plugin is not at all related to opencommand.

> it refuses to list the builds

You mean the plugin isn't loaded at all? Please provide specific info.

> I've tried to reset the builds config and it seems to work fine

This means you made an error in editing the config if it only breaks when you add them. Be sure to follow the guideline at the top of the config file.

**Comment by Penelopeep** [comment]
Hi, usually if the plugin works in "default" state then it just works on the version of grasscutter that you're using.
So I'm guessing that you made some errors in builds, may I see the builds.json file and console error if there're any?

**Comment by Stanstillplays** [comment]
[builds.json](https://github.com/Penelopeep/CharacterBuilder/files/13792038/builds.json)
Here you go m8, I made added builds to, Ayato, Xiao, Venti, Shogun, Itto, Miko, Eula, Keqing, Albedo, Zhongli, Kazuha, Shenhe, Ayaka, Kokomi, Yoimiya, Bennet, Hu Tao, Diluc and Xiangling, in otherwords about half the characters hehe. (Also You responded much quicker than I thought you would Thanks)

**Comment by NotThorny** [comment]
You have a duplicate closure on 501.

**Comment by Penelopeep** [comment]
I'm on my phone so maybe thoronium will find something, but for me it looks fine. But I'm not sure about this lv21. Shouldn't be lv20 instead?

**Comment by Stanstillplays** [comment]
What does that mean? sorry to say.

**Comment by Stanstillplays** [comment]
> ###
> [Dec 29, 2023](#issuecomment-1871842703)

ok the commands from the tool thing said 21 but I'll change it to see what happens

**Comment by NotThorny** [comment]
You need to remove the duplicate closure on line 501.

**Comment by Penelopeep** [comment]
In the "Shougun" part you have "]," two times.
Also if you have lv21 from opencommands then it should be fine.

**Comment by Penelopeep** [comment]
![IMG_20231229_094357.jpg](https://github.com/Penelopeep/CharacterBuilder/assets/81880849/85232d86-99de-4362-bf34-c481d25d5e2f)

**Comment by Stanstillplays** [comment]
ok I finally looked back at this tab and found that error Thanks you guys, now to test it

**Comment by Stanstillplays** [comment]
![image](https://github.com/Penelopeep/CharacterBuilder/assets/112261572/2c7fddff-1928-4af6-abba-560fe0a13f13)
uuuuuuuuh no, it didn't work sorry.

**Comment by Penelopeep** [comment]
Can you check if you have any other errors in the console? Maybe plugin isn't loading at all?

**Comment by Stanstillplays** [comment]
I ran /build again on Keqing and this is what the console gave me, no errors but a bunch of text so IDK
![image](https://github.com/Penelopeep/CharacterBuilder/assets/112261572/940f310c-27c2-480a-bde9-ee234320bf78)

**Comment by Penelopeep** [comment]
You're missing commas in ayato God build.
Also this "text" is an error :)

**Comment by Stanstillplays** [comment]
Alright The commas have been updated, I'll have a look if I missed anyone else.

**Comment by Stanstillplays** [comment]
Missed them in Xiao's Set aswell, added all the commas needed, I don't think that'll fix the feedback problem but I'll give it a go

**Comment by Stanstillplays** [comment]
that also didn't work but here is an updated error log
![image](https://github.com/Penelopeep/CharacterBuilder/assets/112261572/6ad54a65-c788-400c-b1b9-6ccd074d29c6)

**Comment by Penelopeep** [comment]
Now you have double "]," under hutao's crimson2 set

**Comment by Stanstillplays** [comment]
Man I need to look Over my things better thanks, fixed it.

**Comment by Stanstillplays** [comment]
OMG ITS fixed

**Comment by Stanstillplays** [comment]
In Game thank you so much so yes it was just my coding being bad THANK YOU

**Comment by Stanstillplays** [comment]
sorry for the bother, enjoy your days

**Comment by Penelopeep** [comment]
No problem, have a nice day
